[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "static"

[functions]
  external_node_modules = ["serverless-wsgi"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
